#!/usr/bin/env bash

# The goal of this script is to take a directory and install
# all the fonts inside.
# On top of this the script should be able to do this silently
# or verbose. Also the script should be able to keep or delete
# the original file.
#
# Syntax should look like this in the end:
# addfont [flags] directory
current_path="$1"
name=$(basename $current_path)
original_type='' # Possible original_types: archive, directory, file
supported_formats=('ttf' 'otf') # TODO: Add woff

is_command() {
    command -v "$1" >/dev/null
}

install_woff_converter() {
    git clone https://github.com/bramstein/sfnt2woff-zopfli.git woff &&
    cd woff &&
    make &&
    chmod 755 woff2sfnt-zopfli sfnt2woff-zopfli &&
    mv woff2sfnt-zopfli sfnt2woff-zopfli /usr/local/bin &&
    cd .. &&
    rm -rf ./woff
}

is_font() {
    local file_format="${name##*.}"
    for supported_format in "${supported_formats[@]}"; do
        if [[ $supported_format = $file_format ]]; then
            original_type='file'
            return 0
        fi
    done
    return 1
}

add_font() {
    cp -n $1 ~/Library/Fonts/
    if [[ $? -eq 0 ]]; then
        echo "Successfully installed $(basename $1)."
    else
        echo "$(basename $1) is already installed."
    fi
}

add_fonts() {
    find_fonts_in_directory | while read font
    do
        add_font $font
    done
}

clean_up() {
    [[ $original_type = 'archive' ]] &&  rm -rf $current_path
}

find_fonts_in_directory() {
    find $current_path -iname "*.[ot]tf"
}

extract_from_archive() {
    # Creates a folder that we need to delete in the end.
    case $current_path in
        *.tar|*.tgz) tar -xzf "$current_path";;
        *.gzip) gunzip -k "$current_path";;
        *.zip) unzip -qq "$current_path";;
    esac
    
    name="${name%.*}"
    current_path="$PWD/$name"
    original_type='archive'
    main $current_path
    # TODO: Find a better way to get the returned file/directory's path
    #       This right now only works for directories
}

main() {
    if [[ -d "$1" ]]; then
        [[ -z $original_type ]] && original_type='directory' 
    elif [[ -f "$1" ]]; then
        if is_font; then
            add_font $current_path
            exit 0
        else
            extract_from_archive
            exit 0
        fi
    else 
        echo "The path you've entered is not valid: $1"
        exit 128
    fi
    add_fonts
    clean_up
}

main $1 

